name: tiktok_video_downloader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  receive_intent: ^0.2.5
  share_plus: ^7.2.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - imgs/
    - fonts/
